export const communicationList = {
	mailer: {
		unique: 'mailer/get',
		paginate: 'mailer/table',
		save: 'mailer/save',
		edit: 'mailer/edit',
		delete: 'mailer/delete',
	},
	mail: {
		unique: 'mail/get',
		paginate: 'mail/table',
		save: 'mail/save',
		edit: 'mail/edit',
		delete: 'mail/delete',
		send: 'mail/send',
		read: 'mail/getRead',
		list: 'mail/tableRead',
	},
	mailreceiver: {
		unique: 'mailreceiver/get',
		paginate: 'mailreceiver/table',
		save: 'mailreceiver/save',
		edit: 'mailreceiver/edit',
		delete: 'mailreceiver/delete',
	},
	mailattachment: {
		unique: 'mailattachment/get',
		paginate: 'mailattachment/table',
		save: 'mailattachment/save',
		edit: 'mailattachment/edit',
		delete: 'mailattachment/delete',
	},
	mailcid: {
		unique: 'mailcid/get',
		paginate: 'mailcid/table',
		save: 'mailcid/save',
		edit: 'mailcid/edit',
		delete: 'mailcid/delete',
	},
	phone: {
		unique: 'phone/get',
		paginate: 'phone/table',
		save: 'phone/save',
		edit: 'phone/edit',
		delete: 'phone/delete',
		read: 'phone/getRead',
		list: 'phone/tableRead',
	},
	phonereceiver: {
		unique: 'phonereceiver/get',
		paginate: 'phonereceiver/table',
		save: 'phonereceiver/save',
		edit: 'phonereceiver/edit',
		delete: 'phonereceiver/delete',
	},
};
