# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

starter: &starter
  - step:
      name: "Avvio pipelina"
      script:
        - echo "La pipeline sta partendo"

releaseprod: &releaseprod
  - step:
      name: "Version release prod"
      script:
        - echo "Rilasciata una release su prod"

releasetest: &releasetest
  - step:
      name: "Version release test"
      script:
        - echo "Rilasciata una release su test"

deployprod: &deployprod
  - step:
      name: "Copia dei file di prod"
      image: node:10.15.0
      caches:
            - node
      script:        
        - npm install
        - rm -rf ./node_modules/pdfjs-dist/types                
        - npm run build::prod
        - cp -R ./src/config/deploy/prod/. ./dist/keyemporium-web 
      artifacts:
        - dist/**
        - node_modules/**

deploytest: &deploytest
  - step:
      name: "Copia dei file di test"
      image: node:10.15.0
      caches:
            - node
      script:        
        - npm install
        - rm -rf ./node_modules/pdfjs-dist/types                
        - npm run build::test
        - cp -R ./src/config/deploy/test/. /dist/keyemporium-web
      artifacts:
        - dist/**
        - node_modules/**

initprod: &initprod
  - step:
      name: "Iniazilizzazione di git su prod"
      image: wagnerstephan/bitbucket-git-ftp:latest
      script:
        - echo "Sto inizializzando git ftp su prod"
        - git ftp init --syncroot ./dist/keyemporium-web/ -u "okdq_giuseppe" -p "u1CMVe_sPIAG" ftp://okdq.ftp.infomaniak.com/sites/modweb.com

inittest: &inittest
  - step:
      name: "Iniazilizzazione di git su test"
      image: wagnerstephan/bitbucket-git-ftp:latest
      script:
        - echo "Sto inizializzando git ftp su test"
        - git ftp init --syncroot ./dist/keyemporium-web/ -u "okdq_giuseppe" -p "u1CMVe_sPIAG" ftp://okdq.ftp.infomaniak.com/sites/keyemporium.info

pushallprod: &pushallprod
  - step:
      name: "push all dei dati su prod"
      image: wagnerstephan/bitbucket-git-ftp:latest
      script:
        - echo "Sto copiando i files su prod"
        - git ftp push --syncroot ./dist/keyemporium-web/ -u "okdq_giuseppe" -p "u1CMVe_sPIAG" ftp://okdq.ftp.infomaniak.com/sites/modweb.com --all

pushalltest: &pushalltest
  - step:
      name: "push all dei dati su test"
      image: wagnerstephan/bitbucket-git-ftp:latest
      script:
        - echo "Sto copiando i files su test"
        - git ftp push --syncroot ./dist/keyemporium-web/ -u "okdq_giuseppe" -p "u1CMVe_sPIAG" ftp://okdq.ftp.infomaniak.com/sites/keyemporium.info --all

pushprod: &pushprod
  - step:
      name: "push dei dati su prod"
      image: wagnerstephan/bitbucket-git-ftp:latest
      script:
        - echo "Sto copiando i files su prod"
        - git ftp push --syncroot ./dist/keyemporium-web/ -u "okdq_giuseppe" -p "u1CMVe_sPIAG" ftp://okdq.ftp.infomaniak.com/sites/modweb.com

pushtest: &pushtest
  - step:
      name: "push dei dati su test"
      image: wagnerstephan/bitbucket-git-ftp:latest
      script:
        - echo "Sto copiando i files su test"
        - git ftp push --syncroot ./dist/keyemporium-web/ -u "okdq_giuseppe" -p "u1CMVe_sPIAG" ftp://okdq.ftp.infomaniak.com/sites/keyemporium.info

pipelines:
  custom:    
    deploy-prod:
      - <<: *deployprod
    deploy-test:
      - <<: *deploytest
    init-prod:
      - <<: *deployprod
      - <<: *initprod
    init-test:
      - <<: *deploytest
      - <<: *inittest
    push-prod:
      - <<: *pushprod
    push-test:
      - <<: *pushtest
    push-all-prod:
      - <<: *pushallprod
    push-all-test:
      - <<: *pushalltest
  tags:
    v*:
      - parallel:
          - <<: *releasetest
          - <<: *releaseprod
    test-*:            
      - <<: *deploytest
      - <<: *pushtest
    prod-*:            
      - <<: *deployprod
      - <<: *pushprod
