export const shopWarehouseList = {
	brand: {
		unique: 'brand/get',
		paginate: 'brand/table',
		save: 'brand/save',
		edit: 'brand/edit',
		delete: 'brand/delete',
	},
	brandattachment: {
		unique: 'brandattachment/get',
		paginate: 'brandattachment/table',
		save: 'brandattachment/save',
		edit: 'brandattachment/edit',
		delete: 'brandattachment/delete',
	},
	brandreference: {
		unique: 'brandreference/get',
		paginate: 'brandreference/table',
		save: 'brandreference/save',
		edit: 'brandreference/edit',
		delete: 'brandreference/delete',
	},
	category: {
		unique: 'category/get',
		paginate: 'category/table',
		save: 'category/save',
		edit: 'category/edit',
		delete: 'category/delete',
	},
	categoryattachment: {
		unique: 'categoryattachment/get',
		paginate: 'categoryattachment/table',
		save: 'categoryattachment/save',
		edit: 'categoryattachment/edit',
		delete: 'categoryattachment/delete',
	},
	discount: {
		unique: 'discount/get',
		paginate: 'discount/table',
		save: 'discount/save',
		edit: 'discount/edit',
		delete: 'discount/delete',
	},
	pocket: {
		unique: 'pocket/get',
		paginate: 'pocket/table',
		save: 'pocket/save',
		edit: 'pocket/edit',
		delete: 'pocket/delete',
		addProduct: 'pocket/addProduct',
		addService: 'pocket/addService',
		addPrice: 'pocket/addPrice',
		editPrice: 'pocket/editPrice',
		addDiscount: 'pocket/addDiscount',
		editDiscount: 'pocket/editDiscount',
		deleteDiscount: 'pocket/deleteDiscount',
		addTax: 'pocket/addTax',
		editTax: 'pocket/editTax',
		deleteTax: 'pocket/deleteTax',
	},
	pocketattachment: {
		unique: 'pocketattachment/get',
		paginate: 'pocketattachment/table',
		save: 'pocketattachment/save',
		edit: 'pocketattachment/edit',
		delete: 'pocketattachment/delete',
	},
	pocketdiscount: {
		unique: 'pocketdiscount/get',
		paginate: 'pocketdiscount/table',
		save: 'pocketdiscount/save',
		edit: 'pocketdiscount/edit',
		delete: 'pocketdiscount/delete',
	},
	pocketproduct: {
		unique: 'pocketproduct/get',
		paginate: 'pocketproduct/table',
		save: 'pocketproduct/save',
		edit: 'pocketproduct/edit',
		delete: 'pocketproduct/delete',
	},
	pocketreservesetting: {
		unique: 'pocketreservesetting/get',
		paginate: 'pocketreservesetting/table',
		save: 'pocketreservesetting/save',
		edit: 'pocketreservesetting/edit',
		delete: 'pocketreservesetting/delete',
	},
	pocketservice: {
		unique: 'pocketservice/get',
		paginate: 'pocketservice/table',
		save: 'pocketservice/save',
		edit: 'pocketservice/edit',
		delete: 'pocketservice/delete',
	},
	pockettax: {
		unique: 'pockettax/get',
		paginate: 'pockettax/table',
		save: 'pockettax/save',
		edit: 'pockettax/edit',
		delete: 'pockettax/delete',
	},
	price: {
		unique: 'price/get',
		paginate: 'price/table',
		save: 'price/save',
		edit: 'price/edit',
		delete: 'price/delete',
	},
	product: {
		unique: 'product/get',
		paginate: 'product/table',
		save: 'product/save',
		edit: 'product/edit',
		delete: 'product/delete',
		addPrice: 'product/addPrice',
		editPrice: 'product/editPrice',
		addDiscount: 'product/addDiscount',
		editDiscount: 'product/editDiscount',
		deleteDiscount: 'product/deleteDiscount',
		addTax: 'product/addTax',
		editTax: 'product/editTax',
		deleteTax: 'product/deleteTax',
	},
	productattachment: {
		unique: 'productattachment/get',
		paginate: 'productattachment/table',
		save: 'productattachment/save',
		edit: 'productattachment/edit',
		delete: 'productattachment/delete',
	},
	productdiscount: {
		unique: 'productdiscount/get',
		paginate: 'productdiscount/table',
		save: 'productdiscount/save',
		edit: 'productdiscount/edit',
		delete: 'productdiscount/delete',
	},
	productreservesetting: {
		unique: 'productreservesetting/get',
		paginate: 'productreservesetting/table',
		save: 'productreservesetting/save',
		edit: 'productreservesetting/edit',
		delete: 'productreservesetting/delete',
	},
	producttax: {
		unique: 'producttax/get',
		paginate: 'producttax/table',
		save: 'producttax/save',
		edit: 'producttax/edit',
		delete: 'producttax/delete',
	},
	reservationsetting: {
		unique: 'reservationsetting/get',
		paginate: 'reservationsetting/table',
		save: 'reservationsetting/save',
		edit: 'reservationsetting/edit',
		delete: 'reservationsetting/delete',
	},
	service: {
		unique: 'service/get',
		paginate: 'service/table',
		save: 'service/save',
		edit: 'service/edit',
		delete: 'service/delete',
		addPrice: 'service/addPrice',
		editPrice: 'service/editPrice',
		addDiscount: 'service/addDiscount',
		editDiscount: 'service/editDiscount',
		deleteDiscount: 'service/deleteDiscount',
		addTax: 'service/addTax',
		editTax: 'service/editTax',
		deleteTax: 'service/deleteTax',
	},
	serviceattachment: {
		unique: 'serviceattachment/get',
		paginate: 'serviceattachment/table',
		save: 'serviceattachment/save',
		edit: 'serviceattachment/edit',
		delete: 'serviceattachment/delete',
	},
	servicediscount: {
		unique: 'servicediscount/get',
		paginate: 'servicediscount/table',
		save: 'servicediscount/save',
		edit: 'servicediscount/edit',
		delete: 'servicediscount/delete',
	},
	servicereservesetting: {
		unique: 'servicereservesetting/get',
		paginate: 'servicereservesetting/table',
		save: 'servicereservesetting/save',
		edit: 'servicereservesetting/edit',
		delete: 'servicereservesetting/delete',
	},
	servicetax: {
		unique: 'servicetax/get',
		paginate: 'servicetax/table',
		save: 'servicetax/save',
		edit: 'servicetax/edit',
		delete: 'servicetax/delete',
	},
	ticket: {
		unique: 'ticket/get',
		paginate: 'ticket/table',
		save: 'ticket/save',
		edit: 'ticket/edit',
		delete: 'ticket/delete',
		addPrice: 'ticket/addPrice',
		editPrice: 'ticket/editPrice',
		addDiscount: 'ticket/addDiscount',
		editDiscount: 'ticket/editDiscount',
		deleteDiscount: 'ticket/deleteDiscount',
		addTax: 'ticket/addTax',
		editTax: 'ticket/editTax',
		deleteTax: 'ticket/deleteTax',
	},
	ticketattachment: {
		unique: 'ticketattachment/get',
		paginate: 'ticketattachment/table',
		save: 'ticketattachment/save',
		edit: 'ticketattachment/edit',
		delete: 'ticketattachment/delete',
	},
	ticketdiscount: {
		unique: 'ticketdiscount/get',
		paginate: 'ticketdiscount/table',
		save: 'ticketdiscount/save',
		edit: 'ticketdiscount/edit',
		delete: 'ticketdiscount/delete',
	},
	ticketreservesetting: {
		unique: 'ticketreservesetting/get',
		paginate: 'ticketreservesetting/table',
		save: 'ticketreservesetting/save',
		edit: 'ticketreservesetting/edit',
		delete: 'ticketreservesetting/delete',
	},
	tickettax: {
		unique: 'tickettax/get',
		paginate: 'tickettax/table',
		save: 'tickettax/save',
		edit: 'tickettax/edit',
		delete: 'tickettax/delete',
	},
};
