export const WorkCompanyList = {
	activityuser: {
		unique: 'activityuser/get',
		paginate: 'activityuser/table',
		save: 'activityuser/save',
		edit: 'activityuser/edit',
		delete: 'activityuser/delete',
	},
	activityproject: {
		unique: 'activityproject/get',
		paginate: 'activityproject/table',
		save: 'activityproject/save',
		edit: 'activityproject/edit',
		delete: 'activityproject/delete',
	},
	projecttask: {
		unique: 'projecttask/get',
		paginate: 'projecttask/table',
		save: 'projecttask/save',
		edit: 'projecttask/edit',
		delete: 'projecttask/delete',
	},
	projectuser: {
		unique: 'projectuser/get',
		paginate: 'projectuser/table',
		save: 'projectuser/save',
		edit: 'projectuser/edit',
		delete: 'projectuser/delete',
	},
	taskusecase: {
		unique: 'taskusecase/get',
		paginate: 'taskusecase/table',
		save: 'taskusecase/save',
		edit: 'taskusecase/edit',
		delete: 'taskusecase/delete',
	},
	taskuser: {
		unique: 'taskuser/get',
		paginate: 'taskuser/table',
		save: 'taskuser/save',
		edit: 'taskuser/edit',
		delete: 'taskuser/delete',
	},
	usecaseoperation: {
		unique: 'usecaseoperation/get',
		paginate: 'usecaseoperation/table',
		save: 'usecaseoperation/save',
		edit: 'usecaseoperation/edit',
		delete: 'usecaseoperation/delete',
	},
	workexperience: {
		unique: 'workexperience/get',
		paginate: 'workexperience/table',
		save: 'workexperience/save',
		edit: 'workexperience/edit',
		delete: 'workexperience/delete',
	},
	workexperiencecompany: {
		unique: 'workexperiencecompany/get',
		paginate: 'workexperiencecompany/table',
		save: 'workexperiencecompany/save',
		edit: 'workexperiencecompany/edit',
		delete: 'workexperiencecompany/delete',
	},
	workexperiencerole: {
		unique: 'workexperiencerole/get',
		paginate: 'workexperiencerole/table',
		save: 'workexperiencerole/save',
		edit: 'workexperiencerole/edit',
		delete: 'workexperiencerole/delete',
	},
	workexperienceskill: {
		unique: 'workexperienceskill/get',
		paginate: 'workexperienceskill/table',
		save: 'workexperienceskill/save',
		edit: 'workexperienceskill/edit',
		delete: 'workexperienceskill/delete',
	},
	workrole: {
		unique: 'workrole/get',
		paginate: 'workrole/table',
		save: 'workrole/save',
		edit: 'workrole/edit',
		delete: 'workrole/delete',
	},
	workskill: {
		unique: 'workskill/get',
		paginate: 'workskill/table',
		save: 'workskill/save',
		edit: 'workskill/edit',
		delete: 'workskill/delete',
	},
};
