export enum EnumTypeMime {
	APPLICATION = 'application',
	AUDIO = 'audio',
	CHEMICAL = 'chemical',
	DRAWING = 'drawing',
	IWORLD = 'i-world',
	IMAGE = 'image',
	MESSAGE = 'message',
	MODEL = 'model',
	MULTIPART = 'multipart',
	MUSIC = 'music',
	PALEOVU = 'paleovu',
	TEXT = 'text',
	VIDEO = 'video',
	WINDOWS = 'windows',
	WWW = 'www',
	XCONFERENCE = 'x-conference',
	XMUSIC = 'x-music',
	XWORLD = 'x-world',
	XGL = 'xgl',
	GENERIC_EMBED = '1',
	GENERIC_IFRAME = '2',
	YOUTUBE = '3',
}
