name: CI -> Deploy TEST
on:
  push:
    tags:
      - "t*"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ""

      - name: show files
        run: |
          dir
          mkdir dist
          xcopy src\config\deply\test\ dist\${{ secrets.APP_NAME }} /E/Y
